name: GoldShop
version: '1.0'
main: me.squishyslime.goldShop.Main
api-version: '1.21'
load: STARTUP
authors: [ SquishySlime ]
description: An economy system designed to ease the managing of a Minecraft server.
commands:
  gs:
    permission: gs.cmd
    aliases: goldshop
  money:
    permission: gs.money.cmd
    aliases: mon
  bal:
    aliases: [balance]